// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACIGXpm2M5ayvi3USaxTJijJfjrqX1jOQ',
    appId: '1:162407581126:web:cfae44c00e474989351ec7',
    messagingSenderId: '162407581126',
    projectId: 'note-8864b',
    authDomain: 'note-8864b.firebaseapp.com',
    storageBucket: 'note-8864b.appspot.com',
    measurementId: 'G-SRM6WEM22F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzN_DWVYCv7jIhEWDfMImb_L63Gvxyj4',
    appId: '1:162407581126:android:de6cb93df01dbbcf351ec7',
    messagingSenderId: '162407581126',
    projectId: 'note-8864b',
    storageBucket: 'note-8864b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSmUY9ryDSNCilbAuxmmSVq4vPj2-N9Y',
    appId: '1:162407581126:ios:b7fe833a4c6a241e351ec7',
    messagingSenderId: '162407581126',
    projectId: 'note-8864b',
    storageBucket: 'note-8864b.appspot.com',
    iosClientId: '162407581126-8err8n3rnn4sc0b0agm3al158d1f1eft.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
